const $=id=>document.getElementById(id);let expCount=0,eduCount=0,cropper=null,croppedPhoto=null;
const saved=JSON.parse(localStorage.getItem('curriculopro-data')||'null');
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function addExperience(data={}){expCount++;const el=document.createElement('div');el.className='experience';el.innerHTML=`<div class="row"><label>Empresa<input class="exp-company" placeholder="Empresa"></label><label>Cargo<input class="exp-role" placeholder="Cargo"></label></div><div class="row"><label>Período<input class="exp-period" placeholder="2022 - 2025"></label><label>Local<input class="exp-location" placeholder="Cidade - UF"></label></div><label>Atividades e resultados<textarea class="exp-desc" rows="3" placeholder="Descreva suas principais atividades e resultados."></textarea></label><button type="button" class="remove">Remover</button>`;el.querySelector('.exp-company').value=data.company||'';el.querySelector('.exp-role').value=data.role||'';el.querySelector('.exp-period').value=data.period||'';el.querySelector('.exp-location').value=data.location||'';el.querySelector('.exp-desc').value=data.desc||'';el.querySelector('.remove').onclick=()=>{el.remove();saveData()};$('experienceList').appendChild(el)}
function addEducation(data={}){eduCount++;const el=document.createElement('div');el.className='education';el.innerHTML=`<div class="row"><label>Curso<input class="edu-course" placeholder="Curso"></label><label>Instituição<input class="edu-school" placeholder="Instituição"></label></div><div class="row"><label>Período<input class="edu-period" placeholder="2020 - 2023"></label><label>Situação<input class="edu-status" placeholder="Concluído"></label></div><button type="button" class="remove">Remover</button>`;el.querySelector('.edu-course').value=data.course||'';el.querySelector('.edu-school').value=data.school||'';el.querySelector('.edu-period').value=data.period||'';el.querySelector('.edu-status').value=data.status||'';el.querySelector('.remove').onclick=()=>{el.remove();saveData()};$('educationList').appendChild(el)}
function improveText(text,role){if(!text.trim())return `Profissional ${role||'com experiência'} com perfil responsável, organizado e orientado a resultados. Experiência em rotinas profissionais, colaboração em equipe e resolução de problemas, com foco em qualidade e cumprimento de prazos.`;let t=text.trim().replace(/\s+/g,' ');if(!/[.!?]$/.test(t))t+='.';return `${t} Atuação com foco em qualidade, organização, produtividade e cumprimento de prazos.`}
function getData(){return{name:$('name').value,role:$('role').value,location:$('location').value,phone:$('phone').value,email:$('email').value,summary:$('summary').value,skills:$('skills').value,photo:croppedPhoto||'',experience:[...document.querySelectorAll('.experience')].map(e=>({company:e.querySelector('.exp-company').value,role:e.querySelector('.exp-role').value,period:e.querySelector('.exp-period').value,location:e.querySelector('.exp-location').value,desc:e.querySelector('.exp-desc').value})),education:[...document.querySelectorAll('.education')].map(e=>({course:e.querySelector('.edu-course').value,school:e.querySelector('.edu-school').value,period:e.querySelector('.edu-period').value,status:e.querySelector('.edu-status').value}))}}
function saveData(){localStorage.setItem('curriculopro-data',JSON.stringify(getData()))}
function updatePhotoThumb(){const t=$('photoThumb');if(croppedPhoto)t.innerHTML=`<img src="${croppedPhoto}" alt="Foto selecionada">`;else t.innerHTML='<span>Foto</span>'}
function render(){saveData();const d=getData();const name=esc(d.name)||'Seu Nome',role=esc(d.role)||'Profissional';let ex=d.experience.map(e=>{if(!(e.company||e.role||e.desc))return '';return `<div class="cv-item"><strong>${esc(e.role)||'Cargo'}${e.company?' — '+esc(e.company):''}</strong><small>${esc(e.period)}${e.period&&e.location?' • ':''}${esc(e.location)}</small><p>${esc(e.desc)}</p></div>`}).join('');let ed=d.education.map(e=>e.course||e.school?`<div class="cv-item"><strong>${esc(e.course)||'Formação'}</strong><small>${esc(e.school)}${e.school&&e.period?' • ':''}${esc(e.period)}${e.status?' • '+esc(e.status):''}</small></div>`:'').join('');const skills=esc(d.skills).split(',').map(x=>x.trim()).filter(Boolean).join(' • ');const photo=d.photo?`<div class="cv-photo"><img src="${d.photo}" alt="Foto profissional"></div>`:'';$('resumePreview').innerHTML=`<div class="cv-header">${photo}<div class="cv-header-info"><h1 class="cv-name">${name}</h1><div class="cv-role">${role}</div><div class="cv-contact">${[d.location,d.phone,d.email].map(esc).filter(Boolean).join(' • ')}</div></div></div>${d.summary?`<div class="cv-section">PERFIL</div><p class="cv-item"><span class="summary-print">${esc(d.summary)}</span></p>`:''}${ex?`<div class="cv-section">EXPERIÊNCIA PROFISSIONAL</div>${ex}`:''}${ed?`<div class="cv-section">FORMAÇÃO</div>${ed}`:''}${skills?`<div class="cv-section">COMPETÊNCIAS</div><div class="cv-skills">${skills}</div>`:''}`;$('downloadPdf').disabled=false;updatePhotoThumb()}
function restore(){if(!saved)return;['name','role','location','phone','email','summary','skills'].forEach(id=>{if(saved[id]!=null)$(id).value=saved[id]});croppedPhoto=saved.photo||null;$('experienceList').innerHTML='';$('educationList').innerHTML='';(saved.experience||[]).forEach(addExperience);(saved.education||[]).forEach(addEducation);render()}
const stop=new Set(['de','da','do','das','dos','e','a','o','as','os','em','no','na','nos','nas','para','por','com','um','uma','que','se','ao','à','como','ou','mais','ser','ter','é','sua','seu','the','and','for','with','from','this','that']);
function keywords(text){const words=(text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9+#.]{3,}/g)||[]);const freq={};words.forEach(w=>{if(!stop.has(w))freq[w]=(freq[w]||0)+1});return Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,30).map(x=>x[0])}
$('analyzeJob').onclick=()=>{const job=$('jobDescription').value.trim();if(!job){$('analysisResult').innerHTML='<p class="warning">Cole uma descrição de vaga para analisar.</p>';return}const d=getData();const cv=JSON.stringify(d).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const ks=keywords(job);const found=ks.filter(k=>cv.includes(k)),missing=ks.filter(k=>!cv.includes(k));const score=Math.min(100,Math.round((found.length/Math.max(1,ks.length))*100));$('analysisResult').innerHTML=`<div class="score"><span>${score}%</span><div><b>Compatibilidade por palavras-chave</b><small>${found.length} de ${ks.length} termos relevantes encontrados</small></div></div><div class="keyword-columns"><div><h3>✓ Encontradas</h3><p>${found.length?found.map(esc).join(' • '):'Nenhuma encontrada ainda.'}</p></div><div><h3>+ Para considerar</h3><p>${missing.length?missing.map(esc).join(' • '):'Ótimo — não foram identificadas lacunas.'}</p></div></div><small class="disclaimer">Esta é uma análise simples de palavras-chave; não representa uma avaliação oficial de ATS.</small>`}
function openCrop(file){const reader=new FileReader();reader.onload=e=>{$('cropImage').src=e.target.result;$('cropModal').classList.add('open');$('cropModal').setAttribute('aria-hidden','false');if(cropper)cropper.destroy();cropper=new Cropper($('cropImage'),{aspectRatio:1,viewMode:1,dragMode:'move',autoCropArea:.9,background:false,zoomable:true,rotatable:false});};reader.readAsDataURL(file)}
$('photoInput').onchange=e=>{const file=e.target.files[0];if(file)openCrop(file);e.target.value=''};
function closeCrop(){if(cropper){cropper.destroy();cropper=null}$('cropModal').classList.remove('open');$('cropModal').setAttribute('aria-hidden','true')}
$('applyCrop').onclick=()=>{if(!cropper)return;croppedPhoto=cropper.getCroppedCanvas({width:500,height:500,imageSmoothingQuality:'high'}).toDataURL('image/jpeg',.9);updatePhotoThumb();closeCrop();saveData();render()};$('closeCrop').onclick=closeCrop;$('cancelCrop').onclick=closeCrop;$('cropModal').onclick=e=>{if(e.target===$('cropModal'))closeCrop()};$('removePhoto').onclick=()=>{croppedPhoto=null;updatePhotoThumb();saveData();render()};
$('addExperience').onclick=()=>addExperience();$('addEducation').onclick=()=>addEducation();$('resumeForm').onsubmit=e=>{e.preventDefault();render();$('resumePreview').scrollIntoView({behavior:'smooth',block:'nearest'})};$('improveSummary').onclick=()=>{$('summary').value=improveText($('summary').value,$('role').value);$('improveSummary').textContent='✓ Texto melhorado';saveData();setTimeout(()=>$('improveSummary').textContent='✦ Melhorar texto',1800)};$('clearForm').onclick=()=>{if(confirm('Limpar todos os dados?')){localStorage.removeItem('curriculopro-data');croppedPhoto=null;$('resumeForm').reset();$('experienceList').innerHTML='';$('educationList').innerHTML='';addExperience();addEducation();updatePhotoThumb();$('resumePreview').innerHTML='<div class="empty-preview"><div>CV</div><p>Preencha seus dados e clique em<br><b>“Gerar meu currículo”</b>.</p></div>';$('downloadPdf').disabled=true}};$('downloadPdf').onclick=()=>{const el=$('resumePreview');html2pdf().set({margin:.35,filename:`curriculo-${($('name').value||'profissional').toLowerCase().replace(/\s+/g,'-')}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'in',format:'a4',orientation:'portrait'}}).from(el).save()};restore();if(!saved){addExperience();addEducation();updatePhotoThumb()}
