const $=id=>document.getElementById(id);let expCount=0,eduCount=0,cropper=null,croppedPhoto=null,currentTemplate='modern';
const saved=JSON.parse(localStorage.getItem('curriculopro-data')||'null');
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function addExperience(data={}){expCount++;const el=document.createElement('div');el.className='experience';el.innerHTML=`<div class="row"><label>Empresa<input class="exp-company" placeholder="Empresa"></label><label>Cargo<input class="exp-role" placeholder="Cargo"></label></div><div class="row"><label>Período<input class="exp-period" placeholder="2022 - 2025"></label><label>Local<input class="exp-location" placeholder="Cidade - UF"></label></div><label>Atividades e resultados<textarea class="exp-desc" rows="3" placeholder="Descreva suas principais atividades e resultados."></textarea></label><button type="button" class="remove">Remover</button>`;el.querySelector('.exp-company').value=data.company||'';el.querySelector('.exp-role').value=data.role||'';el.querySelector('.exp-period').value=data.period||'';el.querySelector('.exp-location').value=data.location||'';el.querySelector('.exp-desc').value=data.desc||'';el.querySelector('.remove').onclick=()=>{el.remove();saveData()};$('experienceList').appendChild(el)}
function addEducation(data={}){eduCount++;const el=document.createElement('div');el.className='education';el.innerHTML=`<div class="row"><label>Curso<input class="edu-course" placeholder="Curso"></label><label>Instituição<input class="edu-school" placeholder="Instituição"></label></div><div class="row"><label>Período<input class="edu-period" placeholder="2020 - 2023"></label><label>Situação<input class="edu-status" placeholder="Concluído"></label></div><button type="button" class="remove">Remover</button>`;el.querySelector('.edu-course').value=data.course||'';el.querySelector('.edu-school').value=data.school||'';el.querySelector('.edu-period').value=data.period||'';el.querySelector('.edu-status').value=data.status||'';el.querySelector('.remove').onclick=()=>{el.remove();saveData()};$('educationList').appendChild(el)}
function improveText(text,role){if(!text.trim())return `Profissional ${role||'com experiência'} com perfil responsável, organizado e orientado a resultados. Experiência em rotinas profissionais, colaboração em equipe e resolução de problemas, com foco em qualidade e cumprimento de prazos.`;let t=text.trim().replace(/\s+/g,' ');if(!/[.!?]$/.test(t))t+='.';return `${t} Atuação com foco em qualidade, organização, produtividade e cumprimento de prazos.`}
function getData(){return{name:$('name').value,role:$('role').value,location:$('location').value,phone:$('phone').value,email:$('email').value,linkedin:$('linkedin').value,portfolio:$('portfolio').value,objective:$('objective').value,summary:$('summary').value,skills:$('skills').value,courses:$('courses').value,languages:$('languages').value,photo:croppedPhoto||'',template:currentTemplate,experience:[...document.querySelectorAll('.experience')].map(e=>({company:e.querySelector('.exp-company').value,role:e.querySelector('.exp-role').value,period:e.querySelector('.exp-period').value,location:e.querySelector('.exp-location').value,desc:e.querySelector('.exp-desc').value})),education:[...document.querySelectorAll('.education')].map(e=>({course:e.querySelector('.edu-course').value,school:e.querySelector('.edu-school').value,period:e.querySelector('.edu-period').value,status:e.querySelector('.edu-status').value}))}}
function saveData(){localStorage.setItem('curriculopro-data',JSON.stringify(getData()))}
function updatePhotoThumb(){const t=$('photoThumb');if(croppedPhoto)t.innerHTML=`<img src="${croppedPhoto}" alt="Foto selecionada">`;else t.innerHTML='<span>Foto</span>'}
function render(){const d=getData();const name=esc(d.name)||'Seu Nome',role=esc(d.role)||'Profissional';let ex=d.experience.map(e=>{if(!(e.company||e.role||e.desc))return '';return `<div class="cv-item"><strong>${esc(e.role)||'Cargo'}${e.company?' — '+esc(e.company):''}</strong><small>${esc(e.period)}${e.period&&e.location?' • ':''}${esc(e.location)}</small><p>${esc(e.desc)}</p></div>`}).join('');let ed=d.education.map(e=>e.course||e.school?`<div class="cv-item"><strong>${esc(e.course)||'Formação'}</strong><small>${esc(e.school)}${e.school&&e.period?' • ':''}${esc(e.period)}${e.status?' • '+esc(e.status):''}</small></div>`:'').join('');const skills=esc(d.skills).split(',').map(x=>x.trim()).filter(Boolean).join(' • ');const links=[d.location,d.phone,d.email,d.linkedin,d.portfolio].map(esc).filter(Boolean).join(' • ');const photo=d.photo?`<div class="cv-photo"><img src="${d.photo}" alt="Foto profissional"></div>`:'';$('resumePreview').className=`resume-paper ${currentTemplate}`;$('resumePreview').innerHTML=`<div class="cv-header">${photo}<div class="cv-header-info"><h1 class="cv-name">${name}</h1><div class="cv-role">${role}</div><div class="cv-contact">${links}</div></div></div>${d.objective?`<div class="cv-section">OBJETIVO PROFISSIONAL</div><p class="cv-item"><span class="summary-print">${esc(d.objective)}</span></p>`:''}${d.summary?`<div class="cv-section">RESUMO PROFISSIONAL</div><p class="cv-item"><span class="summary-print">${esc(d.summary)}</span></p>`:''}${ex?`<div class="cv-section">EXPERIÊNCIA PROFISSIONAL</div>${ex}`:''}${ed?`<div class="cv-section">FORMAÇÃO</div>${ed}`:''}${skills?`<div class="cv-section">HABILIDADES</div><div class="cv-skills">${skills}</div>`:''}${d.courses?`<div class="cv-section">CURSOS</div><div class="cv-courses">${esc(d.courses)}</div>`:''}${d.languages?`<div class="cv-section">IDIOMAS</div><div class="cv-languages">${esc(d.languages)}</div>`:''}`;$('downloadPdf').disabled=false;updatePhotoThumb();$('templateSelect').value=currentTemplate;document.querySelectorAll('.template').forEach(b=>b.classList.toggle('active',b.dataset.template===currentTemplate));saveData()}
function restore(){if(!saved)return;['name','role','location','phone','email','linkedin','portfolio','objective','summary','skills','courses','languages'].forEach(id=>{if(saved[id]!=null&&$(id))$(id).value=saved[id]});croppedPhoto=saved.photo||null;currentTemplate=saved.template||'modern';$('experienceList').innerHTML='';$('educationList').innerHTML='';(saved.experience||[]).forEach(addExperience);(saved.education||[]).forEach(addEducation);render()}
const stop=new Set(['de','da','do','das','dos','e','a','o','as','os','em','no','na','nos','nas','para','por','com','um','uma','que','se','ao','à','como','ou','mais','ser','ter','é','sua','seu','the','and','for','with','from','this','that']);
function keywords(text){const words=(text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9+#.]{3,}/g)||[]);const freq={};words.forEach(w=>{if(!stop.has(w))freq[w]=(freq[w]||0)+1});return Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,30).map(x=>x[0])}
$('analyzeJob').onclick=()=>{const job=$('jobDescription').value.trim();if(!job){$('analysisResult').innerHTML='<p class="warning">Cole uma descrição de vaga para analisar.</p>';return}const d=getData();const cv=JSON.stringify(d).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const ks=keywords(job);const found=ks.filter(k=>cv.includes(k)),missing=ks.filter(k=>!cv.includes(k));const score=Math.min(100,Math.round((found.length/Math.max(1,ks.length))*100));$('analysisResult').innerHTML=`<div class="score"><span>${score}%</span><div><b>Compatibilidade por palavras-chave</b><small>${found.length} de ${ks.length} termos relevantes encontrados</small></div></div><div class="keyword-columns"><div><h3>✓ Encontradas</h3><p>${found.length?found.map(esc).join(' • '):'Nenhuma encontrada ainda.'}</p></div><div><h3>+ Para considerar</h3><p>${missing.length?missing.map(esc).join(' • '):'Ótimo — não foram identificadas lacunas.'}</p></div></div><small class="disclaimer">Análise indicativa por palavras-chave; não representa uma avaliação oficial de ATS.</small>`}
function normalizeImage(file){return new Promise((resolve,reject)=>{const fallback=()=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)};if(!window.createImageBitmap){fallback();return}createImageBitmap(file,{imageOrientation:'from-image'}).then(bitmap=>{const max=1800,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();resolve(canvas.toDataURL('image/jpeg',.95))}).catch(fallback)})}
function openCrop(file){normalizeImage(file).then(src=>{$('cropImage').src=src;$('cropModal').classList.add('open');$('cropModal').setAttribute('aria-hidden','false');if(cropper)cropper.destroy();cropper=new Cropper($('cropImage'),{aspectRatio:4/5,viewMode:1,dragMode:'move',autoCropArea:.82,background:false,zoomable:true,rotatable:false,responsive:true});$('zoomRange').value=25}).catch(()=>alert('Não foi possível carregar esta foto.'))}
$('photoInput').onchange=e=>{const file=e.target.files[0];if(file)openCrop(file);e.target.value=''};
function closeCrop(){if(cropper){cropper.destroy();cropper=null}$('cropModal').classList.remove('open');$('cropModal').setAttribute('aria-hidden','true')}
$('zoomRange').oninput=e=>{if(cropper)cropper.zoomTo(.25+(Number(e.target.value)/100)*1.5)};
$('applyCrop').onclick=()=>{if(!cropper)return;croppedPhoto=cropper.getCroppedCanvas({width:640,height:800,imageSmoothingEnabled:true,imageSmoothingQuality:'high'}).toDataURL('image/jpeg',.92);closeCrop();saveData();render()};$('closeCrop').onclick=closeCrop;$('cancelCrop').onclick=closeCrop;$('cropModal').onclick=e=>{if(e.target===$('cropModal'))closeCrop()};$('removePhoto').onclick=()=>{croppedPhoto=null;updatePhotoThumb();saveData();render()};
function chooseTemplate(name){currentTemplate=name;saveData();render()}
document.querySelectorAll('.template').forEach(b=>b.onclick=()=>chooseTemplate(b.dataset.template));$('templateSelect').onchange=e=>chooseTemplate(e.target.value);
$('addExperience').onclick=()=>addExperience();$('addEducation').onclick=()=>addEducation();$('resumeForm').onsubmit=e=>{e.preventDefault();render();$('resumePreview').scrollIntoView({behavior:'smooth',block:'nearest'})};$('improveSummary').onclick=()=>{$('summary').value=improveText($('summary').value,$('role').value);$('improveSummary').textContent='✓ Texto melhorado';saveData();setTimeout(()=>$('improveSummary').textContent='✦ Melhorar texto',1800)};$('clearForm').onclick=()=>{if(confirm('Limpar todos os dados?')){localStorage.removeItem('curriculopro-data');croppedPhoto=null;currentTemplate='modern';$('resumeForm').reset();$('experienceList').innerHTML='';$('educationList').innerHTML='';addExperience();addEducation();updatePhotoThumb();$('resumePreview').innerHTML='<div class="empty-preview"><div>CV</div><p>Preencha seus dados e veja<br>seu currículo aqui.</p></div>';$('downloadPdf').disabled=true}};
async function waitForImages(root){const imgs=[...root.querySelectorAll('img')];await Promise.all(imgs.map(img=>{if(img.complete)return img.decode?.().catch(()=>{})||Promise.resolve();return new Promise(resolve=>{img.onload=()=>resolve();img.onerror=()=>resolve()})}))}
async function downloadPDF(){const source=$('resumePreview');if(!source)return;render();if(window.renderExtras)window.renderExtras();await new Promise(r=>setTimeout(r,150));await waitForImages(source);if(!window.html2canvas||!window.jspdf?.jsPDF){alert('O módulo de PDF ainda não carregou. Atualize a página e tente novamente.');return}
const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-10000px;top:0;width:794px;background:#fff;z-index:-1;overflow:visible;';const clone=source.cloneNode(true);clone.style.cssText='width:794px;min-height:1123px;height:auto;margin:0;background:#fff;box-shadow:none;transform:none;overflow:visible;';holder.appendChild(clone);document.body.appendChild(holder);await waitForImages(clone);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
try{const canvas=await html2canvas(clone,{scale:2,useCORS:true,allowTaint:true,backgroundColor:'#ffffff',logging:false,windowWidth:794,scrollX:0,scrollY:0});const pdf=new jspdf.jsPDF({unit:'mm',format:'a4',orientation:'portrait'});const pageW=210,pageH=297,margin=8,usableW=pageW-margin*2,pxPerPage=Math.floor(canvas.width*(pageH-margin*2)/usableW);let offset=0,page=0;while(offset<canvas.height){if(page>0)pdf.addPage();const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=Math.min(pxPerPage,canvas.height-offset);slice.getContext('2d').drawImage(canvas,0,offset,canvas.width,slice.height,0,0,slice.width,slice.height);const ratio=usableW/slice.width;const h=slice.height*ratio;pdf.addImage(slice.toDataURL('image/jpeg',.95),'JPEG',margin,margin,usableW,h,undefined,'FAST');offset+=slice.height;page++}const filename=`curriculo-${(($('name')?.value||'profissional').trim()).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'profissional'}.pdf`;pdf.save(filename)}catch(err){console.error(err);alert('Não foi possível gerar o PDF. Tente novamente após atualizar a página.')}finally{holder.remove()}}
$('downloadPdf').onclick=downloadPDF;$('downloadPdfSide').onclick=downloadPDF;
restore();if(!saved){addExperience();addEducation();updatePhotoThumb()}
